spring.application.name=app
server.port=8081

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dzagjxodyalwnbcirlas.supabase.co/auth/v1

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.root=INFO
logging.level.payment.app=DEBUG
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
logging.pattern.console=%-5level [%thread] [%X{correlationId}] %logger{36} - %msg%n
#logging.structured.format.console=logstash #ecs or golf for prod